config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  authenticated :user do
    root to: 'welcome#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/profile//users/:id', to: 'profile#show', as: :profile_show
  mount Commontator::Engine => 'api/v1/commontator'
  get '/search', to: 'search#show', as: :search_show
  get '/messages', to: 'messages#index', as: :messages_home
  post '/message', to: 'messages#create', as: :message_create
  mount ActionCable.server, at: '/cable'

  namespace 'api' do
    namespace 'v1' do
      get '/users', to: 'users#index'
      resources :users, only: [:show] do
        member do
          delete :delete_image_attachment
          get :avatar_image_thumbnail
        end
      end
      resources :follows, only: [:index, :new, :create, :destroy] do
        member do
          get :allfollowers
          get :allfollowing
        end
      end
      post '/isfollowing', to: 'follows#isfollowing?'
      resources :reviews
      resources :user_reviews
    end
  end

  resources :trips do
    member do
      delete :delete_image_attachment
    end
  end

  resources :payments do
    member do
      put :extend_my_plan
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, dependent: :destroy
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :pro_user_authentication

  def index
    @messages = Message.custom_display
    @message = Message.new
  end

  def create
    message = Message.new(message_params)
    message.user = current_user
    payment = Payment.find_by(user_id: current_user.id)
    if payment.message_count > 0
      payment.message_count -= 1 if payment.message_count > 0
      if payment.save
        if message.save
          ActionCable.server.broadcast 'messages_channel', update_message: message_render(message)
        end
      end
    elsif payment.message_count == -1
      if message.save
        ActionCable.server.broadcast 'messages_channel', update_message: message_render(message)
      end
    elsif payment.message_count == 0
      flash[:notice] = 'You are out of messages'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end

  def pro_user_authentication
    if !current_user.has_role? :pro_user_1
    elsif !current_user.has_role? :pro_user_2
    elsif !current_user.has_role? :pro_user_3
    else
      flash[:alert] = 'You have to be paid user to access message funcationality'
      redirect_to root_path
    end
  end
end

app/views/messages/_message.html.erb
<div class="d-flex justify-content-start mb-4">
  <div class="img_cont_msg">
    <%= image_tag user_avatar(message.user, 40), class: "rounded-circle" %>
  </div>
  <div class="msg_cotainer">
    <div class="text_body">
      <%= message.body %>
    </div>
    <div class="msg_time"><%= time_ago_in_words(message.created_at) %> ago by <%= message.user.name %></div>
  </div>
</div>

app/views/messages/index.html.erb
<div class="container messages">
  <div class="card text-center">
    <div class="card-header">
      Messages
    </div>
    <div id="messages">
      <div class="card-body" id="message_container">
        <%= render @messages %>
      </div>
    </div>
    <div class="card-footer text-muted">
      <%= form_for(@message, url: message_create_path, remote: true) do |f| %>
        <div class="input-group mb-3">
          <%= f.text_field :body, class: "form-control", placeholder: "Type message" %>
          <div class="input-group-append">
            <%= f.button "Send", class: "btn btn-outline-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
    scroll_bottom = function () {
        if ($('#messages').length > 0) {
            $('#messages').scrollTop($('#messages')[0].scrollHeight)
        }
    }

    submit_message = function () {
        $('#message_body').on('keydown', function (e) {
            if (e.keyCode == 13) {
                $('.input-group-append button').click();
                $('#message_body').val("");
            }
        })
    }

    $(document).on('turbolinks:load', function () {
        scroll_bottom()
        submit_message()
    })
</script>