config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  authenticated :user do
    root to: 'welcome#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/profile//users/:id', to: 'profile#show', as: :profile_show
  mount Commontator::Engine => 'api/v1/commontator'
  get '/search', to: 'search#show', as: :search_show
  get '/messages', to: 'messages#index', as: :messages_home
  post '/message', to: 'messages#create', as: :message_create
  mount ActionCable.server, at: '/cable'

  namespace 'api' do
    namespace 'v1' do
      get '/users', to: 'users#index'
      resources :users, only: [:show] do
        member do
          delete :delete_image_attachment
          get :avatar_image_thumbnail
        end
      end
      resources :follows, only: [:index, :new, :create, :destroy] do
        member do
          get :allfollowers
          get :allfollowing
        end
      end
      post '/isfollowing', to: 'follows#isfollowing?'
      resources :reviews
      resources :user_reviews
    end
  end

  resources :trips do
    member do
      delete :delete_image_attachment
    end
  end

  resources :payments do
    member do
      put :extend_my_plan
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    @search_term = params[:search]
    @users = User.search(params[:search])
    @trips = Trip.search(params[:search])
  end
end

app/views/search/show.html.erb
<div class="container search_results">
  <% if @users.empty? && @trips.empty? %>
    <h4>There is no results for "<%= @search_term %>"</h4>
  <% end %>
  <% if !@users.empty? %>
    <div class="search_users">
      <h4>User search results for "<%= @search_term %>"</h4>
      <div class="search_users_cards">
        <% @users.each do |user| %>
          <div class="card col-lg-3 col-md-5 col-sm-8 text-center">
            <div class="card-body">
              <div>
                <%= image_tag user_avatar(user, 40), class: "rounded-circle" %>
              </div>
              <div>
                <h5 class="card-title"><%= link_to user.name.titleize, profile_show_path(user) %></h5>
              </div>
              <div>
                <h6 class="card-subtitle mb-2 text-muted"><%= user.email %></h6>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if !@trips.empty? %>
    <h4>Trip search results for "<%= @search_term %>"</h4>
    <div class="search_trips">
      <% @trips.each do |trip| %>
        <div class="card col-lg-3 col-md-5 col-sm-8" id="<%= trip.id %>">
          <ul class="list-group list-group-flush">
            <div class="card-body">
              <li class="list-group-item">
                <div id="first_item">
                  <%= image_tag user_avatar(trip.user, 50), class: "rounded-circle" %>
                  <a href="/profile/users/<%= trip.user.id %>"><h5 class="card-title"><%= trip.user.name %></h5></a>
                </div>
              </li>
              <li class="list-group-item">
                <div class="trip_image">
                  <% if !trip.photos.present? %>
                    <%= image_tag trip.thumbnail %>
                  <% else %>
                    <%= image_tag trip_image(trip) %>
                  <% end %>
                </div>
              </li>
              <li class="list-group-item  text-center">
                <div id="location">
                  <h5 class="card-title" style="margin: auto"><%= link_to trip.location, trip_path(trip) %></h5>
                  <p style="margin: auto"><%= Time.new(trip.date_s[6...10], trip.date_s[3...5], trip.date_s[0...2]).strftime("%d %b %Y") %>
                    to <%= Time.new(trip.date_e[6...10], trip.date_e[3...5], trip.date_e[0...2]).strftime("%d %b %Y") %></p>
                </div>
              </li>
              <li class="list-group-item  text-center">
                <div>
                  <p class="card-text" style="margin: auto">Some quick example text to build on the card title and make
                    up
                    the bulk of the card's content.</p>
                </div>
              </li>
            </div>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
</div>