config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  authenticated :user do
    root to: 'welcome#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/profile//users/:id', to: 'profile#show', as: :profile_show
  mount Commontator::Engine => 'api/v1/commontator'
  get '/search', to: 'search#show', as: :search_show
  get '/messages', to: 'messages#index', as: :messages_home
  post '/message', to: 'messages#create', as: :message_create
  mount ActionCable.server, at: '/cable'

  namespace 'api' do
    namespace 'v1' do
      get '/users', to: 'users#index'
      resources :users, only: [:show] do
        member do
          delete :delete_image_attachment
          get :avatar_image_thumbnail
        end
      end
      resources :follows, only: [:index, :new, :create, :destroy] do
        member do
          get :allfollowers
          get :allfollowing
        end
      end
      post '/isfollowing', to: 'follows#isfollowing?'
      resources :reviews
      resources :user_reviews
    end
  end

  resources :trips do
    member do
      delete :delete_image_attachment
    end
  end

  resources :payments do
    member do
      put :extend_my_plan
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  before_create :set_expiration_date
  belongs_to :user

  validates :card_number, presence: true
  validates :card_name, presence: true
  validates :code, presence: true
  validates :date_exp, presence: true

  def set_expiration_date
    self.exp_date = Time.now + 30.days
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payment = Payment.new
  end

  def show
    # show a certain payment
  end

  def new
    @payment = Payment.new
  end

  def create
    user_id = params[:payment][:user]
    user = User.find(user_id)
    @payment = Payment.new(payment_params)
    @payment.user = user
    if payment_params[:plan].to_i == 1
      @payment.message_count = 10
    elsif payment_params[:plan].to_i == 2
      @payment.message_count = 100
    elsif payment_params[:plan].to_i == 3
      @payment.message_count = -1
    end
    if @payment.save
      user.grant 'pro_user_' + payment_params[:plan]
      if user.save
        flash[:notice] = 'You are now a premium user'
        redirect_to messages_home_path
      end
    else
      render action: :new
    end
  end

  def update
    user_id = params[:id]
    user = User.find(user_id)
    payment = Payment.find_by(user: user)
    current_plan = payment.plan
    payment.plan = params[:payment][:plan]
    if current_plan != 3
      if payment_params[:plan].to_i == 1
        payment.message_count += 10
        payment.exp_date = Time.now + 30.days
      elsif payment_params[:plan].to_i == 2
        payment.message_count += 100
        payment.exp_date = Time.now + 30.days
      elsif payment_params[:plan].to_i == 3
        payment.message_count = -1
        payment.exp_date = Time.now + 30.days
      end
    else
      days = payment.exp_date - Date.today
      if payment_params[:plan].to_i == 1
        payment.message_count = (days * 100) + 10
        payment.exp_date = Time.now + 30.days
      elsif payment_params[:plan].to_i == 2
        payment.message_count = (days * 100) + 100
        payment.exp_date = Time.now + 30.days
      end
    end
    if payment.save
      user.revoke :pro_user_1 if user.has_role? :pro_user_1
      user.revoke :pro_user_2 if user.has_role? :pro_user_2
      user.revoke :pro_user_3 if user.has_role? :pro_user_3
      user.grant 'pro_user_' + params[:payment][:plan]
      if user.save
        if payment.message_count != -1
          flash[:notice] = 'You now have ' + payment.message_count.to_s + ' messages and your account will expire on ' + payment.exp_date.to_s
        else
          flash[:notice] = 'You now have unlimited messages and your account will expire on ' + payment.exp_date.to_s
        end
        redirect_to messages_home_path
      end
    end
  end

  def extend_my_plan
    user_id = params[:id]
    user = User.find(user_id)
    payment = Payment.find_by(user: user)
    payment.exp_date += 30.days
    current_plan = payment.plan
    if current_plan.to_i == 1
      payment.message_count += 10
    elsif current_plan.to_i == 2
      payment.message_count += 100
    elsif current_plan.to_i == 3
      payment.message_count = -1
    end
    if payment.save
      if payment.message_count != -1
        flash[:notice] = 'You now have ' + payment.message_count.to_s + ' messages and your account will expire on ' + payment.exp_date.to_s
      else
        flash[:notice] = 'You now have unlimited messages and your account will expire on ' + payment.exp_date.to_s
      end
      redirect_to messages_home_path
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:card_number, :card_name, :date_exp, :code, :plan)
  end
end

app/views/payments/_pro_user_1.html.erb
<div class="col-lg-4 col-md-6">
  <div class="card mb-5 mb-lg-0">
    <div class="card-body">
      <h5 class="card-title text-muted text-uppercase text-center">Free</h5>
      <h6 class="card-price text-center">$5<span class="period">/month</span></h6>
      <hr>
      <ul class="fa-ul">
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Single User</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>5GB Storage</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Unlimited Public Projects</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Community Access</li>
        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Unlimited Private Projects</li>
        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Dedicated Phone Support</li>
        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Free Subdomain</li>
        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Monthly Status Reports</li>
      </ul>
      <% if current_user.has_role? :pro_user_1 %>
      <% elsif current_user.has_role? :pro_user_2 %>
      <% elsif current_user.has_role? :pro_user_3 %>
      <% else %>
        <%= link_to "Buy now", new_payment_path(id: "1"), class: "btn btn-block btn-primary text-uppercase" %>
      <% end %>
    </div>
  </div>
</div>

app/views/payments/_pro_user_2.html.erb
<div class="col-lg-4 col-md-6">
  <div class="card mb-5 mb-lg-0">
    <div class="card-body">
      <h5 class="card-title text-muted text-uppercase text-center">Plus</h5>
      <h6 class="card-price text-center">$9<span class="period">/month</span></h6>
      <hr>
      <ul class="fa-ul">
        <li><span class="fa-li"><i class="fa fa-check"></i></span><strong>5 Users</strong></li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>50GB Storage</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Unlimited Public Projects</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Community Access</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Unlimited Private Projects</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Dedicated Phone Support</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Free Subdomain</li>
        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Monthly Status Reports</li>
      </ul>
      <% if current_user.has_role? :pro_user_1 %>
      <% elsif current_user.has_role? :pro_user_2 %>
      <% elsif current_user.has_role? :pro_user_3 %>
      <% else %>
        <%= link_to "Buy now", new_payment_path(id: "2"), class: "btn btn-block btn-primary text-uppercase" %>
      <% end %>
    </div>
  </div>
</div>

app/views/payments/_pro_user_3.html.erb
<div class="col-lg-4 col-md-6">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title text-muted text-uppercase text-center">Pro</h5>
      <h6 class="card-price text-center">$15<span class="period">/month</span></h6>
      <hr>
      <ul class="fa-ul">
        <li><span class="fa-li"><i class="fa fa-check"></i></span><strong>Unlimited Users</strong></li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>150GB Storage</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Unlimited Public Projects</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Community Access</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Unlimited Private Projects</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Dedicated Phone Support</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span><strong>Unlimited</strong> Free Subdomains</li>
        <li><span class="fa-li"><i class="fa fa-check"></i></span>Monthly Status Reports</li>
      </ul>
      <% if current_user.has_role? :pro_user_1 %>
      <% elsif current_user.has_role? :pro_user_2 %>
      <% elsif current_user.has_role? :pro_user_3 %>
      <% else %>
        <%= link_to "Buy now", new_payment_path(id: "3"), class: "btn btn-block btn-primary text-uppercase" %>
      <% end %>
    </div>
  </div>
</div>

app/views/payments/_upgrade_paln.html.erb
<div class="container">
  <h4>You already have a premium plan</h4>
  <% payment = Payment.find_by(user_id: current_user.id) %>
  <% if payment.message_count != -1 %>
    <p>Your plan have <%= payment.message_count %> messages and it will expire on <%= payment.exp_date %></p>
  <% else %>
    <p>Your plan have unlimited messages and it will expire on <%= payment.exp_date %></p>
  <% end %>
</div>

<% if user == :pro_user_1 %>
  <%= form_for(@payment, url: payment_path(current_user), html: { class: "payment_form col-md-5 col-sm-12", method: :put }) do |f| %>
    <div class="form-group">
      <label>You can change your plan here</label>
      <%= f.select :plan, options_for_select([['Plan $9', 2], ['Plan $15', 3]]), class: "form-control" %>
    </div>
    <%= f.submit "Change", :onclick => "return confirm('Are you sure you want to do that?')", class: "btn btn-danger" %>
  <% end %>
<% end %>
<% if user == :pro_user_2 %>
  <%= form_for(@payment, url: payment_path(current_user), html: { class: "payment_form col-md-5 col-sm-12", method: :put }) do |f| %>
    <div class="form-group">
      <label>Select Your Plan</label>
      <%= f.select :plan, options_for_select([['Plan $5', 1], ['Plan $15', 3]]), class: "form-control" %>
    </div>
    <%= f.submit "Change", :onclick => "return confirm('Are you sure you want to do that?')", class: "btn btn-danger" %>
  <% end %>
<% end %>
<% if user == :pro_user_3 %>
  <%= form_for(@payment, url: payment_path(current_user), html: { class: "payment_form col-md-5 col-sm-12", method: :put }) do |f| %>
    <div class="form-group">
      <label>Select Your Plan</label>
      <%= f.select :plan, options_for_select([['Plan $5', 1], ['Plan $9', 2]]), class: "form-control" %>
    </div>
    <%= f.submit "Change", :onclick => "return confirm('Are you sure you want to do that?')", class: "btn btn-danger" %>
  <% end %>
<% end %>

<%= link_to "Extend my plan", extend_my_plan_payment_path(current_user), data: { confirm: "Are you sure you want to do that?" }, method: :put, class: "btn btn-primary" %>

app/views/payments/index.html.erb
<% unless current_user.has_role? :pro_user_1 %>
  <% unless current_user.has_role? :pro_user_2 %>
    <% unless current_user.has_role? :pro_user_3 %>
      <div class="container pricing">
        <div class="row">
          <!-- Free Tier -->
          <%= render partial: 'payments/pro_user_1' %>
          <!-- Plus Tier -->
          <%= render partial: 'payments/pro_user_2' %>
          <!-- Pro Tier -->
          <%= render partial: 'payments/pro_user_3' %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>


<% if current_user.has_role? :pro_user_1 %>
  <div class="container user_premium_user">
    <div class="plan_card col-lg-6 col-md-12 col-sm-12">
      <div class="row">
        <%= render partial: 'payments/pro_user_1' %>
      </div>
    </div>
    <div class="upgrade_card col-lg-6 col-md-12 col-sm-12">
      <%= render partial: 'payments/upgrade_paln', locals: { user: :pro_user_1 } %>
    </div>
  </div>
<% elsif current_user.has_role? :pro_user_2 %>
  <div class="container user_premium_user">
    <div class="plan_card col-lg-6 col-md-12">
      <div class="row">
        <%= render partial: 'payments/pro_user_2' %>
      </div>
    </div>
    <div class="upgrade_card col-lg-6 col-md-12">
      <%= render partial: 'payments/upgrade_paln', locals: { user: :pro_user_2 } %>
    </div>
  </div>
<% elsif current_user.has_role? :pro_user_3 %>
  <div class="container user_premium_user">
    <div class="plan_card col-6">
      <div class="row">
        <%= render partial: 'payments/pro_user_3' %>
      </div>
    </div>
    <div class="upgrade_card col-lg-6 col-md-12">
      <%= render partial: 'payments/upgrade_paln', locals: {user: :pro_user_3} %>
    </div>
  </div>
<% end %>

app/views/payments/new.html.erb
<div class="container payments">
  <div class="plan_details col-md-5 col-sm-12">
    <% if params[:id] == "1" %>
      <%= render partial: 'payments/pro_user_1' %>
    <% elsif params[:id] == "2" %>
      <%= render partial: 'payments/pro_user_2' %>
    <% else %>
      <%= render partial: 'payments/pro_user_3' %>
    <% end %>
  </div>
  <div class="divider col-md-2 col-sm-0">
    <div></div>
  </div>
  <%= form_for(@payment, url: payments_path, method: :post, html: {class: "payment_form col-md-5 col-sm-12"}) do |f| %>
    <%= f.hidden_field :user, value: current_user.id %>
    <div class="panel panel-default">

      <div class="panel-heading">
        <div class="row">
          <h3 class="text-center">Payment Details</h3>
        </div>
      </div>

      <div class="panel-body">
        <form role="form">
          <div class="row">
            <div class="col-xs-12">
              <div class="form-group">
                <label>CARD NUMBER</label>
                <div class="input-group">
                  <i style="position: absolute;margin-top: 10px; z-index: 1; margin-left: 200px" class="fa fa-credit-card fa-1x search_icon"></i>
                  <%= f.text_field :card_number, type: "Number", class: "form-control", placeholder: "Valid Card Number" %>
                  <% if @payment.errors[:card_number].present? %>
                    <div class="form_errors">Card number <%= @payment.errors[:card_number].first %></div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="row year_cvc">
            <div class="col-xs-7 col-md-7">
              <div class="form-group">
                <label><span class="hidden-xs">EXPIRATION</span><span class="visible-xs-inline">EXP</span>
                  DATE</label>
                <%= f.text_field :date_exp, placeholder: "MM/YY", autocomplete: "off", id: "start", class: "datepicker form-control", style: "padding-left: 12px"%>
                <% if @payment.errors[:date_exp].present? %>
                  <div class="form_errors">Expire date <%= @payment.errors[:date_exp].first %></div>
                <% end %>
              </div>
            </div>
            <div class="col-xs-5 col-md-5 pull-right">
              <div class="form-group">
                <label>CV CODE</label>
                <%= f.text_field :code, type: "Number", class: "form-control", placeholder: "CVC" %>
                <% if @payment.errors[:code].present? %>
                  <div class="form_errors">Code <%= @payment.errors[:code].first %></div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <div class="form-group">
                <label>CARD OWNER</label>
                <%= f.text_field :card_name, class: "form-control", placeholder: "Card Owner Name" %>
                <% if @payment.errors[:card_name].present? %>
                  <div class="form_errors">Card name <%= @payment.errors[:card_name].first %></div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <div class="form-group">
                <label>Select Your Plan</label>
                <%= f.select :plan, options_for_select([['Plan $5', 1], ['Plan $9', 2], ['Plan $15', 3]], selected: params[:id]), class: "form-control" %>
                <% if @payment.errors[:plan].present? %>
                  <div class="form_errors">Plan <%= @payment.errors[:plan].first %></div>
                <% end %>
              </div>
            </div>
          </div>
        </form>
      </div>

      <div class="panel-footer">
        <div class="row">
          <div class="col-xs-12">
            <%= f.submit class: "form-control btn btn-danger", placeholder: "Valid Card Number" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
    $(function () {
        $(function () {
            $(".datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "-50:+50",
                dateFormat: "yy-mm-dd"
            });
        });

    });
</script>